spring.application.name=relay
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
# Database Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:54321/veylor_relay}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD}

# Flyway Migration & JPA Configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false
spring.jpa.hibernate.ddl-auto=validate
spring.docker.compose.enabled=false

# Java 21 Virtual Threads Support
spring.threads.virtual.enabled=true

# Admin Config
app.admin.secret-token=${ADMIN_SECRET_TOKEN}

# Dynamic Mail Provider Configuration (Defaults to Mailpit)
spring.mail.host=${MAIL_HOST:localhost}
spring.mail.port=${MAIL_PORT:1025}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.from-address=${MAIL_FROM_ADDRESS:relay@veylor.com}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:false}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS:${MAIL_SMTP_AUTH:false}}
spring.mail.properties.mail.smtp.starttls.required=${MAIL_SMTP_STARTTLS_REQ:${MAIL_SMTP_AUTH:false}}

sentry.dsn=https://075ff1f4dcdb9fe1c3e3e6f3e618b27c@o4510575707357184.ingest.de.sentry.io/4511752919253072
sentry.send-default-pii=${SENTRY_SEND_DEFAULT_PII:false}
