spring.application.name=rest_service
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/veylor_relay}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD}
